### ISSUE TITLE
Beatles Loops Lab broken

### ISSUE THREAD

**Issue by dweinzimmer** [learn-co-curriculum/js-beatles-loops-lab#26]
Hi, 

The Beatles Loops Lab tests will not run properly. Typing in "learn test" right out of the box with no edits whatsoever gives the following results:

```
 0   __,------,
 1   __|  /\_/\
 0   _~|_( x .x)
     _ ""  ""

  0 passing (28ms)
  1 failing

  1)  "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)



npm ERR! Test failed.  See above for more details.
```

This has been replicated by James Rogers (Flatiron) and also by another student. It seems like perhaps some of the dependencies that are loaded are out of date, but I don't understand well enough to diagnose what's causing the problem.

**Comment by dweinzimmer** [comment]
I don't know if this would be solved by merging #25 ?

**Comment by mccarthydanielle** [comment]
This is also happening to me. @dweinzimmer

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @dweinzimmer .

We have updated the materials and believe your issue to have been resolved. Since you have already forked the lesson, order to complete the lab, you will need to delete the fork on your github account. Once you revisit the lab in learn.co, it will re-fork using the updated lesson.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
