### ISSUE TITLE
     Error: Cannot find module 'jsdom/lib/old-api'

### ISSUE THREAD

**Issue by Christopher-Stolfa** [learn-co-curriculum/js-beatles-loops-lab#28]
Iv'e been getting this a lot lately when I type "learn"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Chribtoper.

We have updated the materials and believe your issue to have been resolved. In order to complete the lab if you have already forked it, you must delete the fork that exists on your GitHub account. Once you've deleted it, when you open the lesson on learn.co, it will re-fork from the updated lesson.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
