### ISSUE TITLE
Confused with the 'Foo' 'Bar' on Beatles lab

### ISSUE THREAD

**Issue by Meganimation** [learn-co-curriculum/js-beatles-loops-lab#37]
My code seems to run fine, I add the facts as normal. When entering learn, it expects the terms 'foo' and 'bar' to be added, yet when I add them to the array, it breaks everything. What's going on? And how are 'foo' and 'bar' beatles facts?

**Comment by maxwellbenton** [comment]
HI @Meganimation,

Thank you for providing this feedback. This test is meant to ensure the code you've written is able to work as expected, even if the inputs change. `johnLennonFacts` should loop over whatever array is passed into it. The test itself provides the inputs, so adding them hard-coded into your solution won't work.

I have updated the tests in this lab, however, so that instead of `foo` and `bar`, the test example are additional facts about John. I've also separated this test out so that it has a unique message explaining what is expected.

Thank you for contributing to a Learn lesson!
