### ISSUE TITLE
Running tests for js-beatles-loops-lab-v-000

### ISSUE THREAD

**Issue by Chris-Sexton** [learn-co-curriculum/js-beatles-loops-lab#4]
When I run learn -b in my terminal I get a message saying "This directory doesn't appear to have any specs in it." and the test doesn't show as passing or failing on my learn.co page. I just wanted to see if I am doing something wrong and how to test my code.

**Comment by AnnJohn** [comment]
hi @Chris-Sexton could you use the Ask a Question tool and/or file a bug report. If you click on your profile pic in Learn, you'll see a dropdown menu with an option to report a bug. 

We use this space for issues specifically related to the content in the curriculum so since your issue is a product/technical one, doing the above is the better solution. Thanks!
